Add dnstap recordings for DVE-2017-0007, add updated information abou…
dns-violations/dns-violations pull request #30
Opened 2017-01-30 12:30 UTC by oerdnj

…t  issue fixed

2017-01-30 15:19 UTC, jelu requested changes

2017-01-30 15:19 UTC, jelu commented on 2017/DVE-2017-0007.md
> +There's additional breakagin in the DNS packets as they are malformed
Typo `breakagin` and is this not another DVE?

2017-01-30 15:19 UTC, jelu commented on 2017/DVE-2017-0007.md
> +The authoritative servers were also setting `AD` bit on in all DNS
This also, another DVE?

2017-02-08 09:07 UTC, jelu commented
@oerdnj ping?

2017-02-09 10:55 UTC, oerdnj commented
Ok, I will split it into more DVEs soon..ish.

2017-02-17 11:16 UTC, oerdnj commented on 2017/DVE-2017-0007.md
> +There's additional breakagin in the DNS packets as they are malformed
This is not `DVE-2017-0012`

2017-02-17 11:17 UTC, oerdnj commented on 2017/DVE-2017-0007.md
> +The authoritative servers were also setting `AD` bit on in all DNS
This is now `DVE-2017-0013`

2017-02-17 11:39 UTC, jelu approved these changes

2017-02-17 11:39 UTC, merged