DVE-2017-0011: GitBook CDN nameservers return A records on any QTYPE
dns-violations/dns-violations pull request #35
Opened 2017-02-17 11:05 UTC by oerdnj

2017-02-17 11:41 UTC, jelu requested changes

2017-02-17 11:41 UTC, jelu commented on 2017/DVE-2017-0011.md
> +```
?

2017-02-17 12:25 UTC, oerdnj commented on 2017/DVE-2017-0011.md
> +```
Fixed. And I have also noticed they don't set the 'AA' bit. Anyway I got reponse from their side pretty quick, so this will hopefully get fixed soon.

2017-02-17 12:37 UTC, jelu commented on 2017/DVE-2017-0011.md
> +```
OK, do you want to wait on that before merge?

2017-02-17 12:37 UTC, jelu approved these changes

2017-02-17 13:09 UTC, merged

2017-02-20 10:12 UTC, AaronO commented
@oerdnj I updated your Zendesk Ticket following a deploy last night.

@jelu @oerdnj Do you think you guys could rerun your tests ? With the new changes our DNS now only responds to DNS queries with the following:
* `QClass` is `ANY` or `INET`
* `QType` is `ANY`, `A` or `AAAA`

All other queries get `rcode=NOERROR` with no answer records. Any unexpected errors that happen on our end whilst processing the query now currently return `rcode=SERVFAIL`

2017-02-20 10:43 UTC, oerdnj commented
@AaronO There's a great tool called ZoneMaster that can help you with the basics of DNS protocol: https://www.zonemaster.net/test/eb9ee1ee90c5b526

But right now it fails, because you don't handle `NS` queries.

BTW, since you write your DNS in Go, are you aware of CoreDNS (https://coredns.io/)?

2017-02-20 11:13 UTC, AaronO commented
@oerdnj Do you mean that if fails because I don't return the SOA on NS queries ? Or that for `dig IN NS cdn.gitbook.com @ns1.gitbook.me`. I should return two `NS` records : `ns1.gitbook.me` and `ns2.gitbook.me` ?

Yep I'm aware of CoreDNS, but the master nodes of our CDN do a few extra things on top of answering DNS queries, such as:
- Tracking healthy edge nodes (edge nodes send heartbeats to the master nodes)
    - So if an edge node is down it can't be returned in DNS replies
- DNS geo-balanced replies (matching the closest healthy edge node to the user)
- Providing an API to control edge nodes (cache clearing, etc ...)
- Provisioning SSL certs
- Auto-clustering via `etcd`

That's all nicely packaged and deployed as a single binary. Maybe we could re-use some code from CoreDNS, but I wouldn't want to use it through it's binary and config files, because that would make things harder to maintain and develop than our current setup.

2017-02-20 11:18 UTC, oerdnj commented
> Or that for dig IN NS cdn.gitbook.com @ns1.gitbook.me. I should return two NS records : ns1.gitbook.me and ns2.gitbook.me ?

This ^^^


I am not forcing CoreDNS upon you. It's just ... DNS seems simple at first, but it is hard :), so reusing as much code as possible might prevent some of the mistakes already encountered by others.

2017-02-20 11:20 UTC, oerdnj commented
We started and maintain this list exactly for the reason for others to see what tiny little mistakes have other people made (without judging anyone), so the new implementors could avoid making them.

@AaronO Also I would like to express yet again, that I appreciate the fast response and will to fix your DNS implementation!

2017-02-20 11:25 UTC, jelu commented
@AaronO If you have special domain names which you would like to control then RRs for there are ways of doing it within the authoritative nameserver software that exists today, Knot-DNS has Lua as do PowerDNS and the PowerDNS team also made dnsdist which can act like a proxy.

2017-02-20 11:26 UTC, AaronO commented
Thanks, I'll get that NS fix out sometime later this week.

Sorry if that came across as agressive, CoreDNS is cool, we actually use the developer's underlaying dns library :) So I'll look into using some of CoreDNS' code if possible.

I totally agree, the devil is in the details, I appreciate the community effort to help DNS implementations become standards compliant, hopefully avoiding