Ubuntu 17.10+ fails captive portal authentication with arubanetworks captive portals
dns-violations/dns-violations pull request #56
Opened 2018-02-09 11:52 UTC by xnox

Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

2018-03-02 10:15 UTC, shane-kerr requested changes
Other than a typo in the DVE number assigned, this looks good to me.

2018-03-02 10:15 UTC, shane-kerr commented on 2018/DVE-2018-0001.md
> +# DVE-2017-0001: securelogin.arubanetworks.com captive Wi-Fi portals fail to authorise with Ubuntu 17.10+ / systemd-resolved clients
`DVE-2018-0001` probably.

2018-03-02 12:06 UTC, xnox commented on 2018/DVE-2018-0001.md
> +# DVE-2017-0001: securelogin.arubanetworks.com captive Wi-Fi portals fail to authorise with Ubuntu 17.10+ / systemd-resolved clients
bah

2018-03-02 13:04 UTC, shane-kerr approved these changes
Looks good to me.

2018-03-21 10:45 UTC, oerdnj approved these changes

2018-03-21 10:45 UTC, merged